### ISSUE TITLE
Missing package on composer

### ISSUE THREAD

**Issue by DarekTw** [TicketSwap/PaymentPrzelewy24Bundle#1]
Hi

I have tried install PaymentPrzelewy24Bundle and got this message:
The requested package ticketswap/payment-przelewy24-bundle could not be found in any version, there may be a typo in the package name.

I can't find this package at packagist https://packagist.org/search/?q=przelewy24

After add

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/TicketSwap/PaymentPrzelewy24Bundle"
        },
        {
            "type": "vcs",
            "url": "https://github.com/TicketSwap/omnipay-przelewy24"
        }
    ],
```

to composer.json, everything works well, except that there is a problem with symfony 3.1
- omnipay/common 2.5.x-dev requires guzzle/guzzle ~3.9
- guzzle/guzzle v3.9.3 requires symfony/event-dispatcher ~2.1
- don't install symfony/event-dispatcher v2.1.0|don't install symfony/symfony v3.1.0

**Comment by ruudk** [comment]
Thanks for reporting. I've added both packages to packagist.org. Can you confirm that it works now?

The problem with SF3 is that Omnipay is not yet compatible :(

**Comment by DarekTw** [comment]
Thanks for quick reply, it works now.
